// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4mI5Kj61f6E532vg46GnmnnCfsI9XIM',
    appId: '1:793164633643:android:c2f267d67b908274ccfc6e',
    messagingSenderId: '793164633643',
    projectId: 'makecallio',
    authDomain: 'makecallio.firebaseapp.com',
    storageBucket: 'makecallio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4mI5Kj61f6E532vg46GnmnnCfsI9XIM',
    appId: '1:793164633643:android:c2f267d67b908274ccfc6e',
    messagingSenderId: '793164633643',
    projectId: 'makecallio',
    storageBucket: 'makecallio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnZSVzdthE2oa82Vjv8Uy0Wgefx6nGAWs',
    appId: '1:793164633643:ios:1e2ec90f03abf1abccfc6e',
    messagingSenderId: '793164633643',
    projectId: 'makecallio',
    storageBucket: 'makecallio.firebasestorage.app',
    iosBundleId: 'com.olssoo.makecall',
    iosClientId: '793164633643-urj0qb989v8l2bggj6h025plnbbshfg5.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnZSVzdthE2oa82Vjv8Uy0Wgefx6nGAWs',
    appId: '1:793164633643:ios:1e2ec90f03abf1abccfc6e',
    messagingSenderId: '793164633643',
    projectId: 'makecallio',
    storageBucket: 'makecallio.firebasestorage.app',
    iosBundleId: 'com.olssoo.makecall',
    iosClientId: '793164633643-urj0qb989v8l2bggj6h025plnbbshfg5.apps.googleusercontent.com',
  );
}
